version: '3'

services:
  nginx:
    image: nginx:1.14
    container_name: nginx
    volumes:
      - ./code/:/var/www/code
      - ./code/project:/var/www/code/project # 项目映射目录
      - ./logs/:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d/:/etc/nginx/conf.d
      - ./nginx/conf/ssl/:/etc/nginx/ssl
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm
    volumes:
      - ./code/:/var/www/code
      - ./code/project:/var/www/code/project
      - ./supervisor:/etc/supervisor/conf.d
    ports:
      - "5200:5200"
    depends_on:
      - cache

  cache:
    image: redis:5.0
    container_name: cache
    ports:
      - "6379:6379"

  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
      - TZ=Asia/Shanghai
